// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: api/proto/es.proto

package src

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Segment string `protobuf:"bytes,2,opt,name=segment,proto3" json:"segment,omitempty"`
}

func (x *EsRequest) Reset() {
	*x = EsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_es_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EsRequest) ProtoMessage() {}

func (x *EsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_es_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EsRequest.ProtoReflect.Descriptor instead.
func (*EsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_es_proto_rawDescGZIP(), []int{0}
}

func (x *EsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EsRequest) GetSegment() string {
	if x != nil {
		return x.Segment
	}
	return ""
}

type EsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *EsResponse) Reset() {
	*x = EsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_es_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EsResponse) ProtoMessage() {}

func (x *EsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_es_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EsResponse.ProtoReflect.Descriptor instead.
func (*EsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_es_proto_rawDescGZIP(), []int{1}
}

func (x *EsResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_api_proto_es_proto protoreflect.FileDescriptor

var file_api_proto_es_proto_rawDesc = []byte{
	0x0a, 0x12, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x3e, 0x0a, 0x09, 0x45,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x28, 0x0a, 0x0a, 0x45,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x38, 0x0a, 0x09, 0x45, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x2b, 0x0a, 0x02, 0x45, 0x73, 0x12, 0x10, 0x2e, 0x65, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x45, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x65, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x45, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73,
	0x72, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_es_proto_rawDescOnce sync.Once
	file_api_proto_es_proto_rawDescData = file_api_proto_es_proto_rawDesc
)

func file_api_proto_es_proto_rawDescGZIP() []byte {
	file_api_proto_es_proto_rawDescOnce.Do(func() {
		file_api_proto_es_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_es_proto_rawDescData)
	})
	return file_api_proto_es_proto_rawDescData
}

var file_api_proto_es_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_es_proto_goTypes = []interface{}{
	(*EsRequest)(nil),  // 0: es.v1.EsRequest
	(*EsResponse)(nil), // 1: es.v1.EsResponse
}
var file_api_proto_es_proto_depIdxs = []int32{
	0, // 0: es.v1.EsService.Es:input_type -> es.v1.EsRequest
	1, // 1: es.v1.EsService.Es:output_type -> es.v1.EsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_es_proto_init() }
func file_api_proto_es_proto_init() {
	if File_api_proto_es_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_es_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_es_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_es_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_es_proto_goTypes,
		DependencyIndexes: file_api_proto_es_proto_depIdxs,
		MessageInfos:      file_api_proto_es_proto_msgTypes,
	}.Build()
	File_api_proto_es_proto = out.File
	file_api_proto_es_proto_rawDesc = nil
	file_api_proto_es_proto_goTypes = nil
	file_api_proto_es_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EsServiceClient is the client API for EsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EsServiceClient interface {
	Es(ctx context.Context, in *EsRequest, opts ...grpc.CallOption) (*EsResponse, error)
}

type esServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEsServiceClient(cc grpc.ClientConnInterface) EsServiceClient {
	return &esServiceClient{cc}
}

func (c *esServiceClient) Es(ctx context.Context, in *EsRequest, opts ...grpc.CallOption) (*EsResponse, error) {
	out := new(EsResponse)
	err := c.cc.Invoke(ctx, "/es.v1.EsService/Es", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EsServiceServer is the server API for EsService service.
type EsServiceServer interface {
	Es(context.Context, *EsRequest) (*EsResponse, error)
}

// UnimplementedEsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEsServiceServer struct {
}

func (*UnimplementedEsServiceServer) Es(context.Context, *EsRequest) (*EsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Es not implemented")
}

func RegisterEsServiceServer(s *grpc.Server, srv EsServiceServer) {
	s.RegisterService(&_EsService_serviceDesc, srv)
}

func _EsService_Es_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EsServiceServer).Es(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/es.v1.EsService/Es",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EsServiceServer).Es(ctx, req.(*EsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "es.v1.EsService",
	HandlerType: (*EsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Es",
			Handler:    _EsService_Es_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/es.proto",
}
